// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: TH1

#ifndef _TH1_UI_H
#define _TH1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"

void plus_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_THTarc;
extern lv_obj_t * ui_rminL;
extern lv_obj_t * ui_rmaxL;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_shL;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_ptL;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Button3;
void ui_event_inc(lv_event_t * e);
void ui_event_dec(lv_event_t * e);
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_THTarc2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_heat1_png);    // assets/heat1.png
LV_IMG_DECLARE(ui_img_1871335464);    // assets/pngwing.com (9).png
LV_IMG_DECLARE(ui_img_heat2_png);    // assets/heat2.png
LV_IMG_DECLARE(ui_img_heat3_png);    // assets/heat3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
