// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: test2

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 447);
    lv_obj_set_height(ui_Keyboard1, 157);
    lv_obj_set_x(ui_Keyboard1, -1);
    lv_obj_set_y(ui_Keyboard1, 103);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 438);
    lv_obj_set_height(ui_TextArea1, 213);
    lv_obj_set_x(ui_TextArea1, -1);
    lv_obj_set_y(ui_TextArea1, -107);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);



}
